#!/usr/bin/env node
/**
 * Harness gate — asserts that the agent-facing docs still describe reality.
 *
 * Two modes, one script:
 *   node tools/agent-harness/check-harness.mjs           # --check (default): stale → exit 1
 *   node tools/agent-harness/check-harness.mjs --write    # regenerate the generated blocks
 *
 * What this gate does NOT prove: that any skill or doc is *good*, only that what the docs
 * claim exists actually exists. Semantic quality is a review/LLM job, not a gate's.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { matchWriteRules } from './lib/rules.mjs';
import { missingUserSkills } from './lib/user-skills.mjs';
import guardRules from './rules/pre-guard.rules.json' with { type: 'json' };

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const AGENTS_MD = join(ROOT, 'AGENTS.md');
const SKILLS_DIR = join(ROOT, '.agents/skills');
const THIN_ENTRYPOINTS = ['CLAUDE.md'];
const THIN_MAX_LINES = 60;

const START =
  '<!-- SKILLS:START — auto-generated by tools/agent-harness/check-harness.mjs; do not hand-edit -->';
const END = '<!-- SKILLS:END -->';

const mode = process.argv.includes('--write') ? 'write' : 'check';
const failures = [];
const fail = (message) => failures.push(message);
/** 看得見但不擋人的缺口 —— 不影響 exit code。 */
const warnings = [];

/**
 * `skills-lock.json` 是 AGENTS.md skill 表的真相來源；磁碟用來重生 lock。
 *
 * 由來：skill 一度只有部分進版控（`.agents/` 被 gitignore，但多數檔案在規則加上去之前
 * 就已經在裡面了），CI 的 clone 因此看到部分存在的目錄，第一次跑就紅。現在 skill 全部
 * 進版控，兩個環境看到的是同一份，lock 保留下來作為文件與現實之間的明確接縫。
 */
const LOCK = join(ROOT, 'tools/agent-harness/skills-lock.json');

/** Canonical order: plain alphabetical. Never rely on readdir order — it is platform-dependent. */
function skillsOnDisk() {
  if (!existsSync(SKILLS_DIR)) return null; // 目錄不存在 → 無從比對，不是錯誤
  const names = readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() || entry.isSymbolicLink())
    .map((entry) => entry.name)
    .filter((name) => existsSync(join(SKILLS_DIR, name, 'SKILL.md')))
    .sort();
  return names.map((name) => {
    const entry = { name, description: skillDescription(name) };
    const source = skillOrigin(name);
    if (source) entry.source = source;
    return entry;
  });
}

/**
 * 選擇性的 `ORIGIN` 檔（`<url> <ref>`）記錄該 skill 的 upstream。
 *
 * 只有 angular-scss-bem-standards 有 —— 它原本是一個巢狀 git clone，於是 git 只存了一個
 * 160000 gitlink 而非內容，clone 出來是空目錄（CI 因此紅過）。解除巢狀 repo 之後，
 * upstream 就靠這個檔案留存。其餘 skill 沒有 upstream，就是這份。
 */
function skillOrigin(name) {
  const path = join(SKILLS_DIR, name, 'ORIGIN');
  return existsSync(path) ? readFileSync(path, 'utf8').trim() : null;
}

function skillDescription(name) {
  const source = readFileSync(join(SKILLS_DIR, name, 'SKILL.md'), 'utf8');
  const match = /^description:\s*(.+)$/m.exec(source.slice(0, 2000));
  const text = match ? match[1].trim().replace(/^["']|["']$/g, '') : '';
  return text.length > 110 ? `${text.slice(0, 107)}…` : text;
}

/** 遞迴列出副檔名相符的檔案。A10 / A11 / A12 共用 —— 原本各自帶一份一樣的閉包。 */
function walk(dir, ext) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? walk(join(dir, entry.name), ext)
      : entry.name.endsWith(ext)
        ? [join(dir, entry.name)]
        : [],
  );
}

function readLock() {
  if (!existsSync(LOCK)) return [];
  return JSON.parse(readFileSync(LOCK, 'utf8')).skills ?? [];
}

function renderSkillBlock(skills) {
  if (skills.length === 0) return '_（`skills-lock.json` 目前是空的。）_';
  return [
    '| Skill | 用途 |',
    '| --- | --- |',
    ...skills.map((skill) => `| \`${skill.name}\` | ${skill.description || '—'} |`),
  ].join('\n');
}

function spliceBlock(source, inner) {
  const from = source.indexOf(START);
  const to = source.indexOf(END);
  if (from === -1 || to === -1 || to < from) return null;
  return `${source.slice(0, from + START.length)}\n\n${inner}\n\n${source.slice(to)}`;
}

function currentInner(source) {
  const from = source.indexOf(START);
  const to = source.indexOf(END);
  if (from === -1 || to === -1 || to < from) return null;
  return source.slice(from + START.length, to).trim();
}

/**
 * Compare on content, not on layout. The PostToolUse formatter owns this file and re-aligns
 * markdown table padding after `--write` renders it — comparing raw strings made the gate go
 * red on every prettier run, and regenerating produced output prettier changed right back.
 * Collapsing inter-cell whitespace and separator-row dashes leaves the assertion intact
 * (adding, removing or renaming a skill still changes the normalized form) without the ping-pong.
 */
function normalize(block) {
  return block
    .split('\n')
    .map((line) =>
      line
        .trim()
        .replace(/-{2,}/g, '-')
        .replace(/[ \t]+/g, ' '),
    )
    .filter((line) => line !== '')
    .join('\n');
}

// ── A1a. skills-lock.json 與磁碟一致（只在磁碟有 skill 目錄時，即本機）────────────────────
const onDisk = skillsOnDisk();

if (mode === 'write' && onDisk && onDisk.length > 0) {
  writeFileSync(
    LOCK,
    `${JSON.stringify(
      {
        note: 'AGENTS.md skill 表的真相來源。skill 本身也進版控；這份 manifest 是文件與磁碟之間的明確接縫。重生：npm run harness:write',
        skills: onDisk,
      },
      null,
      2,
    )}\n`,
  );
}

const locked = readLock();

// skill 現在全部進版控，所以 CI 的 clone 與本機看到的是同一份 —— 這個比對兩邊都跑。
// （先前 `.agents/` 被 gitignore 但多數 skill 早已在版控裡，CI 看到的是部分存在的目錄，
//  當時只能用 process.env.CI 跳過。把版控狀態弄一致之後那個 workaround 就不需要了。）
if (mode !== 'write' && onDisk && JSON.stringify(onDisk) !== JSON.stringify(locked)) {
  fail('skills-lock.json 與 .agents/skills/ 磁碟現況不符。重生：npm run harness:write');
}

// ── A6. 每個 skill 在各 CLI 目錄都有 symlink ─────────────────────────────────────────────
// `.agents/skills/` 是真身，其餘 CLI 目錄靠相對 symlink 共用同一份。這個結構會無聲漂掉：
// 實際發生過 —— .codex 少了 angular-scss-bem-standards（而 AGENTS.md 明文要求寫 SCSS 前
// 先 invoke 它），沒有任何東西發現。
const SYMLINK_TARGETS = ['.claude', '.codex'];
// Claude 由 plugin 取得 ui-ux-pro-max，不需要本地副本；其餘 CLI 沒有 plugin 機制。
const SYMLINK_EXEMPT = { '.claude': ['ui-ux-pro-max'] };

for (const dir of SYMLINK_TARGETS) {
  const skillsDir = join(ROOT, dir, 'skills');
  if (!existsSync(skillsDir)) continue;
  const exempt = SYMLINK_EXEMPT[dir] ?? [];
  for (const { name } of locked) {
    if (exempt.includes(name)) continue;
    if (!existsSync(join(skillsDir, name, 'SKILL.md'))) {
      fail(`${dir}/skills/${name} 不存在或斷鏈 —— 該 CLI 叫不到這個 skill。`);
    }
  }
}

// ── A1b. AGENTS.md 的表格與 lock 一致（CI 只驗得到這一段，因為它沒有 skill 檔）───────────
const agentsSource = readFileSync(AGENTS_MD, 'utf8');
const inner = renderSkillBlock(locked);

if (spliceBlock(agentsSource, inner) === null) {
  fail(`AGENTS.md 缺少 SKILLS:START / SKILLS:END marker，無法同步 skill 清單。`);
} else if (mode === 'write') {
  writeFileSync(AGENTS_MD, spliceBlock(agentsSource, inner));
  console.log('✓ AGENTS.md skill 清單已重生');
} else if (normalize(currentInner(agentsSource)) !== normalize(inner)) {
  fail('AGENTS.md 的 skill 清單與 skills-lock.json 不符。重生：npm run harness:write');
}

// ── A2. CLAUDE.md stays a thin importer ──────────────────────────────────────────────────
for (const name of THIN_ENTRYPOINTS) {
  const path = join(ROOT, name);
  if (!existsSync(path)) continue;
  const source = readFileSync(path, 'utf8');
  const lines = source.split('\n').length;
  if (!source.includes('@AGENTS.md')) {
    fail(`${name} 沒有 import AGENTS.md — 專案規則的單一真相是 AGENTS.md（clause c10）。`);
  }
  if (lines > THIN_MAX_LINES) {
    fail(
      `${name} 有 ${lines} 行，超過 ${THIN_MAX_LINES} 行上限 — 規則請寫進 AGENTS.md（clause c10）。`,
    );
  }
}

// ── A3. no parallel documentation tree (clause c9) ───────────────────────────────────────
for (const stray of ['doc', 'docs']) {
  if (existsSync(join(ROOT, stray))) {
    fail(`偵測到 ${stray}/ 目錄。文件只准放 kb/（clause c9）。`);
  }
}

// ── A5. every clause cited anywhere in the harness exists in the constitution ────────────
// The guard blocks a write citing a clause id, and the router tells the agent which clause to
// read. Renumbering the law without updating them points the agent at a phantom article —
// which is exactly what happened the first time these clauses were renumbered.
const constitutionPath = join(ROOT, 'kb/wiki/architecture/constitution.md');
if (!existsSync(constitutionPath)) {
  fail('kb/wiki/architecture/constitution.md 不存在，但 harness 規則引用它。');
} else {
  const law = readFileSync(constitutionPath, 'utf8');
  const declared = new Set([...law.matchAll(/^###\s+(c\d+)\s/gm)].map((match) => match[1]));
  const sources = {
    'pre-guard': 'tools/agent-harness/rules/pre-guard.rules.json',
    'doc-router': 'tools/agent-harness/rules/doc-router.rules.json',
  };
  for (const [label, relPath] of Object.entries(sources)) {
    // ids come from rule.id (pre-guard) and from free text in the router's hints
    const raw = readFileSync(join(ROOT, relPath), 'utf8');
    const cited = [...new Set([...raw.matchAll(/\bc(\d+)\b/g)].map((match) => `c${match[1]}`))];
    for (const id of cited.sort()) {
      if (!declared.has(id)) fail(`${label} 引用了憲法沒有的條款 ${id}（${relPath}）。`);
    }
  }
}

// ── A7. 每一支 API route 掛載時都宣告了可用角色（clause c1）─────────────────────────────
// 這個洞當初長出來的方式：新增 route 時沒有人想到要限制角色，而預設是全開。
// 18 支 route 裡只有 2 支擋了角色，其餘任何登入者（含家長）都讀得到全組織的學生與成績。
// 見 kb/wiki/architecture/role-authorization.md
const apiIndex = join(ROOT, 'apps/api/src/index.ts');
if (existsSync(apiIndex)) {
  const source = readFileSync(apiIndex, 'utf8');

  for (const [, path] of source.matchAll(/app\.route\('(\/api\/[^']+)'/g)) {
    fail(`${path} 用 app.route 掛載，沒有宣告可用角色。改用 mount(path, route, roles)`);
  }

  for (const [call, path] of source.matchAll(/mount\('(\/api\/[^']+)'[^;]*;/g)) {
    // mount(path, route, roles) —— 少了第三個引數就是忘了宣告
    if (call.split(',').length < 3) {
      fail(`${path} 的 mount() 少了角色宣告`);
    }
  }
}

// ── A8. 每張業務表都啟用了 RLS（clause c1 的 fail-closed 後盾）─────────────────────────
// 這是靜態掃 migration 而不是查 DB：gate 在 CI 上跑，那裡沒有資料庫。
// 漂移是這樣發生的：早期的表都有開，後來新增的忘了，而沒有任何東西會提醒。
// 30 張表裡有 16 張就這樣一路沒開。
const MIGRATIONS = join(ROOT, 'supabase/migrations');
if (existsSync(MIGRATIONS)) {
  const sql = readdirSync(MIGRATIONS)
    .filter((f) => f.endsWith('.sql'))
    .map((f) => readFileSync(join(MIGRATIONS, f), 'utf8'))
    .join('\n');

  // Better Auth 的表不歸我們管（c2）
  const created = [
    ...sql.matchAll(/create\s+table\s+(?:if\s+not\s+exists\s+)?(?:public\.)?([a-z_]+)/gi),
  ]
    .map((m) => m[1])
    .filter((name) => !name.startsWith('ba_'));

  const rlsEnabled = new Set(
    [
      ...sql.matchAll(/alter\s+table\s+(?:public\.)?([a-z_]+)\s+enable\s+row\s+level\s+security/gi),
    ].map((m) => m[1]),
  );

  // 建了又刪的不算 —— school_exam_schedules 就是這樣被誤報的
  const dropped = new Set(
    [...sql.matchAll(/drop\s+table\s+(?:if\s+exists\s+)?(?:public\.)?([a-z_]+)/gi)].map(
      (m) => m[1],
    ),
  );

  for (const table of new Set(created)) {
    if (dropped.has(table)) continue;
    if (!rlsEnabled.has(table)) {
      fail(`業務表 ${table} 沒有 ENABLE ROW LEVEL SECURITY（c1 的 fail-closed 後盾）`);
    }
  }
}

// ── A10. 不依賴雲端供應商的專屬服務（clause c12）─────────────────────────────────────────
// c12：客戶必須能夠取走資料、在自己的基礎設施上運行整套系統。用了 Workers KV / R2 /
// Durable Objects 之類的專屬服務，客戶的自架環境就得先有那個東西 —— 離開的權利就消失了。
//
// 限制的是**程式碼**，不是部署目標：部署到 Cloudflare 沒問題，讓程式碼只能跑在
// Cloudflare 才有問題。理由見 kb/wiki/architecture/vendor-relationship.md
const VENDOR_LOCKIN = [
  ['KVNamespace', 'Workers KV'],
  ['DurableObject', 'Durable Objects'],
  ['R2Bucket', 'R2'],
  ['AnalyticsEngineDataset', 'Analytics Engine'],
  ['@cloudflare/ai', 'Workers AI'],
];
const apiSrc = join(ROOT, 'apps/api/src');
if (existsSync(apiSrc)) {
  for (const file of walk(apiSrc, '.ts')) {
    const text = readFileSync(file, 'utf8');
    for (const [token, label] of VENDOR_LOCKIN) {
      if (text.includes(token)) {
        const rel = file.replace(ROOT + '/', '');
        fail(`${rel} 依賴 ${label}（${token}）—— 客戶無法自架（c12）`);
      }
    }
  }
}

// ── A11. createUser 不得帶 password（clause c1 的 CPU 前提）─────────────────────────────
// 密碼雜湊用 scrypt，那是刻意昂貴的演算法（防暴力破解），而 Cloudflare Workers 免費方案
// 每個請求只有 10ms CPU。實測並發 1 也會 503 —— 無法靠改程式碼修好，因為任何安全的
// 密碼雜湊都會超過 10ms。所以整個系統改用 OAuth + 一次性連結，密碼路徑全部移除。
//
// **這條 gate 存在是因為漏過一次**：改的時候記得了 parents.ts 與 staff.ts，
// 漏掉 bootstrap-org.ts。結果是「scrypt 從系統消失」這個宣稱是假的，而且開新站的
// 第一個管理員拿到一組在任何地方都無法輸入的密碼。
//
// Better Auth 的 createUser 明說：不給 password 就是「magic link 或 social login only
// user」——那是官方支援的路。見 kb/wiki/architecture/line-oauth-login.md
if (existsSync(apiSrc)) {
  for (const file of walk(apiSrc, '.ts')) {
    if (file.endsWith('.spec.ts')) continue;
    const text = readFileSync(file, 'utf8');
    // 抓 createUser({ ... }) 的 body，看裡面有沒有 password 這個 key
    for (const m of text.matchAll(/createUser\(\{[\s\S]{0,600}?\}\s*\)/g)) {
      if (/\bpassword\s*[,:]/.test(m[0])) {
        const rel = file.replace(ROOT + '/', '');
        fail(
          `${rel} 的 createUser 帶了 password —— scrypt 會超過 Workers 的 10ms CPU 上限，而且那組密碼沒有任何地方能輸入`,
        );
      }
    }
  }
}

// ── A9. deny 規則指向的檔案真的存在 ────────────────────────────────────────────────────
// deny 規則是路徑字串比對。憲法從 kb/architecture/ 搬到 kb/wiki/architecture/ 時，
// 如果忘了同步更新，護欄會**靜默失效** —— 沒有任何測試會發現，直到有人修了不該修的東西。
// 這次是運氣好記得更新；下次不會。
const settingsPath = join(ROOT, '.claude/settings.json');
if (existsSync(settingsPath)) {
  const settings = JSON.parse(readFileSync(settingsPath, 'utf8'));
  const denies = settings?.permissions?.deny ?? [];

  for (const rule of denies) {
    // 只驗看得出具體路徑的規則：Edit(<path>) 或 Bash(node <path>:*)
    const m = /^(?:Edit|Read|Write)\(([^)*]+)\)$/.exec(rule) ?? /^Bash\(node ([^\s:)]+)/.exec(rule);
    if (!m) continue;
    const target = m[1];
    if (target.includes('*')) continue; // glob 規則無法逐一驗證
    if (!existsSync(join(ROOT, target))) {
      fail(`deny 規則指向不存在的檔案：${rule} —— 檔案搬走時護欄會靜默失效`);
    }
  }
}

// ── A12. 既有 SCSS 裡的 viewport 單位（clause c6）───────────────────────────────────────
// c6 原本只有 PreToolUse hook 守，而 hook 刻意只看**新寫進去的那段文字**
// （`lib/hook-io.mjs` 的 `pendingWrites` 只取 new_string —— 不然修掉違規反而會被擋）。
// 代價是**存量完全沒有覆蓋**：早於 hook 存在、之後沒人重寫過的違規永遠不會被送進判斷。
// `styles.scss` 的 `min-height: 100vh` 就這樣待著，而 enforcement 表上 c6 寫的是「已接」。
//
// 這條補上另一半：用**同一份規則、同一支 matcher** 掃全部既有 .scss。
// 共用而不是另寫一條 regex 是刻意的 —— 兩份會漂掉，而漂掉的方向一定是 gate 比 hook 寬。
const WEB_SRC = join(ROOT, 'apps/web/src');
const c6Rules = guardRules.rules.filter((rule) => rule.id === 'c6');

if (existsSync(WEB_SRC) && c6Rules.length > 0) {
  for (const file of walk(WEB_SRC, '.scss')) {
    const rel = file.replace(ROOT + '/', '');
    readFileSync(file, 'utf8')
      .split('\n')
      .forEach((text, index) => {
        if (matchWriteRules([{ filePath: rel, text }], c6Rules).length > 0) {
          fail(`${rel}:${index + 1} 使用了 viewport 單位（c6）：${text.trim()}`);
        }
      });
  }
}

// kb/ 的內容健康度（frontmatter、索引新鮮度、斷鏈、孤兒頁）由 kb-wiki skill 的 lint 負責，
// 不由 harness gate 管 —— 這跟 fvg 的配置一致：harness 守程式碼與流程，kb-wiki 守知識庫。

// ── W1. 使用者層級 skill 在這台機器上存在嗎（警告，不紅燈）────────────────────────────
// 而那個 kb-wiki skill 不進版控（它是使用者跨專案共用的），所以「AGENTS.md 說得出口的
// 指令」與「這台機器叫得動的指令」之間有一道無聲的縫。這條把縫顯示出來，但不擋 CI ——
// CI 上本來就不會有使用者的 skill。
for (const skill of missingUserSkills()) {
  warnings.push(
    `${skill.name} 是使用者層級 skill，這台機器上找不到 ~/${skill.probe} —— ${skill.why}`,
  );
}

// ── report ───────────────────────────────────────────────────────────────────────────────
// --write 一律 exit 0：它的工作是「修好能自動修的」，剩下的（例如 CLAUDE.md 被塞進規則）
// 本來就得人改。若這裡跟著 exit 1，`harness:write` 的 `&&` 會短路，KB 的 --write 就整個
// 不會跑 —— 踩過一次。真正的把關由隨後的 --check 負責。
if (warnings.length > 0) {
  console.warn(`⚠ harness 有 ${warnings.length} 項提醒（不擋，exit code 不受影響）：`);
  for (const message of warnings) console.warn(`  - ${message}`);
}

if (failures.length > 0 && mode !== 'write') {
  console.error(`✖ harness gate 有 ${failures.length} 項不同步：`);
  for (const message of failures) console.error(`  - ${message}`);
  process.exit(1);
}
if (failures.length > 0) {
  console.warn(`⚠ 另有 ${failures.length} 項無法自動修，需要人工處理（細節跑 npm run harness）`);
} else {
  console.log(`✓ harness gate 全綠（${locked.length} 個 skill）`);
}
