#!/usr/bin/env node
/**
 * 功能區現況表 —— 從磁碟推導，寫進 kb/wiki/roadmap.md 的 marker 區塊。
 *
 *   node tools/agent-harness/feature-map.mjs           # --check：過期 → exit 1
 *   node tools/agent-harness/feature-map.mjs --write    # 重生
 *
 * 為什麼要生成而不是手寫：本專案的 kb/wiki/lessons/backlog-legacy.md 是一張手畫的 ASCII 依賴圖，追蹤 8 個
 * 完成項目，而系統實際有 21 個功能區橫跨三個角色 —— 其中大半是完全沒有後端的空殼。
 * 手寫的狀態表必然腐化（憲法 c11），而路線圖腐化的後果是「不知道自己在哪」。
 *
 * 這張表證明什麼：某個功能區的 UI、API、規格、測試各自存不存在。
 * **不證明**功能正確或完整 —— 一個有 API 呼叫但邏輯全錯的頁面照樣顯示為 built。
 */
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const ROADMAP = join(ROOT, 'kb/wiki/roadmap.md');
/**
 * 三個角色都要掃。
 *
 * 第一版只掃 admin，結果這張表在整個 2026-08 期間都在宣稱「21 個功能區現況」，
 * 卻從來沒看過 teacher 與 parent —— 而 parent 的 11 個頁面全是空殼。
 * 用它排優先順序的人（我）因此得出過「這是唯一沒有畫面的功能」這種結論。
 */
const ROLES = ['admin', 'teacher', 'parent'];
const ROLE_LABELS = { admin: '管理端', teacher: '老師端', parent: '家長端' };
const WEB_FEATURES = join(ROOT, 'apps/web/src/app/features');

/** 頁面一律用 `<role>/<dir>` 稱呼，避免 admin/attendance 與 teacher/attendance 撞名 */
const rolePagesDir = (role) => join(WEB_FEATURES, role, 'pages');
const API_ROUTES = join(ROOT, 'apps/api/src/routes');
const API_INDEX = join(ROOT, 'apps/api/src/index.ts');
const SPECS = join(ROOT, 'kb/wiki/specs');

const START =
  '<!-- FEATURE-MAP:START — auto-generated by tools/agent-harness/feature-map.mjs; do not hand-edit -->';
const END = '<!-- FEATURE-MAP:END -->';

/** kb/specs 底下不屬於任何功能區的檔案 */
/** route 檔名 → 實際掛載路徑，只列不一致的 */
const MOUNT_ALIAS = { 'org-settings': 'org' };

const SPEC_EXEMPT = ['README.md', 'BRAINSTORM_PROMPT.md'];

/**
 * 功能區藍圖。刻意**手寫**而非從磁碟推導 —— 推導的話「規劃了但還沒開始」這個訊號就不存在了。
 * 代價是磁碟上多出來的東西會靜默消失，所以底下有反向斷言把未歸類的項目變成錯誤。
 */
const AREAS = [
  {
    name: '儀表板',
    pages: ['admin/dashboard', 'teacher/dashboard', 'parent/dashboard'],
    routes: ['me'],
    specs: ['admin/dashboard.md', 'teacher/dashboard.md', 'parent/dashboard.md'],
  },
  {
    name: '學生',
    pages: ['admin/students', 'teacher/students'],
    routes: ['students'],
    specs: ['admin/student-affairs/students.md', 'teacher/students.md'],
  },
  {
    name: '家長',
    pages: ['admin/parents'],
    routes: ['parents'],
    specs: ['admin/student-affairs/parents.md'],
  },
  { name: '人員', pages: ['admin/staff'], routes: ['staff'], specs: ['admin/system/staff.md'] },
  { name: '分校', pages: ['admin/campuses'], routes: ['campuses'], specs: ['admin/system/campuses.md'] },
  { name: '學校', pages: ['admin/schools'], routes: ['schools'], specs: [] },
  { name: '科目', pages: ['admin/subjects'], routes: ['subjects'], specs: [] },
  {
    name: '課程與班級',
    pages: ['admin/courses'],
    routes: ['courses', 'classes'],
    specs: ['admin/academic/courses.md', 'admin/academic/classes.md'],
  },
  {
    name: '課表與課堂',
    pages: ['admin/sessions', 'teacher/schedule', 'parent/schedule'],
    routes: ['sessions'],
    specs: [
      'admin/academic/calendar.md',
      'admin/calendar.md',
      'teacher/schedule.md',
      'parent/schedule.md',
    ],
  },
  {
    name: '報名',
    pages: [
      'admin/enrollments',
      'parent/enrollment',
      'parent/add-course',
      'parent/renewal',
      'parent/trial',
    ],
    routes: ['enrollments'],
    specs: [
      'admin/enrollment/enrollment.md',
      'admin/enrollment/enrollment-requests.md',
      'admin/enrollment/renewals.md',
      'admin/enrollment/trials.md',
      'parent/enrollment.md',
      'parent/add-course.md',
      'parent/renewal.md',
      'parent/trial.md',
      'public/enrollment.md',
      'public/trial.md',
    ],
  },
  {
    // P1 金流地基。**目前沒有任何頁面** —— 價目表與收費期間的管理畫面是 P2，
    // 現在只有 API 與 schema。現況表因此三個角色都會顯示未開始，那是正確的。
    name: '計費',
    pages: [],
    routes: ['billing-periods', 'fee-templates'],
    specs: [],
  },
  {
    name: '出勤與到班',
    pages: ['admin/attendance', 'teacher/attendance', 'parent/attendance'],
    routes: ['attendance', 'daily-checkins'],
    specs: [
      'admin/student-affairs/attendance.md',
      'teacher/attendance.md',
      'parent/attendance.md',
      'public/qr-checkin.md',
    ],
  },
  { name: '請假', pages: ['admin/leave'], routes: ['leaves'], specs: ['admin/student-affairs/leave.md'] },
  {
    name: '考試與成績',
    pages: ['admin/grades', 'parent/grades'],
    routes: ['academy-exams', 'school-exams', 'scores'],
    specs: ['admin/student-affairs/grades.md', 'teacher/assessments.md', 'parent/grades.md'],
  },
  {
    name: '餐費',
    pages: ['admin/meals', 'parent/meals'],
    routes: [],
    specs: ['admin/finance/meals.md', 'parent/meals.md'],
  },
  {
    name: '繳費',
    pages: ['admin/payments', 'admin/fee-templates', 'parent/payments'],
    routes: [],
    specs: ['admin/finance/payments.md', 'admin/finance/fee-templates.md', 'parent/payments.md'],
  },
  { name: '報表', pages: ['admin/reports'], routes: [], specs: ['admin/finance/reports.md'] },
  {
    name: '通知',
    pages: ['admin/notifications', 'teacher/notifications', 'parent/notifications'],
    routes: ['announcements'],
    specs: ['admin/notifications.md', 'teacher/notifications.md', 'parent/notifications.md'],
  },
  // 後端沒有自己的 route 檔：`GET /api/sessions/changes` 掛在 sessions 底下（異動紀錄本來就
  // 是課堂的附屬資料）。認領 `sessions` 讓狀態反映「這頁真的接得到後端」。
  { name: '課務異動', pages: ['admin/changes'], routes: ['sessions'], specs: [] },
  {
    name: '系統設定',
    pages: ['admin/settings'],
    routes: ['org-settings'],
    specs: ['admin/system/settings.md'],
  },
  {
    // MVP 明列但磁碟上完全不存在 —— 沒有頁面、route、schema，只在 5 份規格裡被順帶提到。
    // 這種項目一定要手寫進藍圖，否則「規劃了但還沒開始」這個訊號在生成表裡永遠不會出現。
    name: '聯絡簿',
    pages: [],
    routes: [],
    specs: [],
    planned: true,
  },
  {
    name: '身分與稽核',
    pages: [],
    routes: ['audit-logs', 'login-links'],
    specs: ['admin/roles-and-auth.md', 'public/login.md'],
  },
];

function listDirs(dir) {
  return existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true })
        .filter((e) => e.isDirectory())
        .map((e) => e.name)
        .sort()
    : [];
}

function listRoutes() {
  return existsSync(API_ROUTES)
    ? readdirSync(API_ROUTES)
        .filter((f) => f.endsWith('.ts') && !f.endsWith('.spec.ts'))
        .map((f) => f.replace(/\.ts$/, ''))
        .sort()
    : [];
}

function walkSpecs(dir, prefix = '') {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const rel = prefix ? `${prefix}/${e.name}` : e.name;
    if (e.isDirectory()) return walkSpecs(join(dir, e.name), rel);
    // kb-wiki 的 map 會在每個分類生成 _moc.md，那不是規格檔
    return e.name.endsWith('.md') && e.name !== '_moc.md' ? [rel] : [];
  });
}

/**
 * 頁面有沒有真的接後端 = 它 import 了 `@core/<domain>.service`。
 *
 * 第一版找的是頁面目錄裡的字串 `'/api/`，結果 21 個功能區有 18 個被判成空殼 —— 明顯錯誤，
 * 因為這個專案的頁面一律透過 core 的 service 呼叫後端，不直接 fetch。第二版改看
 * `from '@core/`，同樣不行：連空殼都會 import `RouteObj`。
 *
 * 基礎設施 service（overlay/browser-state 之類）不算數：它們是純前端的，
 * 一個只 import 它們的頁面仍然沒有後端。
 */
const INFRA_SERVICES = new Set([
  'overlay-container',
  'browser-state',
  'device',
  'navigation',
  'api',
  'captcha',
  'reference-data',
]);

const WEB_SRC = join(ROOT, 'apps/web/src/app');

/** 把 `@shared/foo/bar.component` 這種別名解析成實體檔案路徑。 */
function resolveAlias(specifier) {
  const m = /^@(shared|core)\/(.+)$/.exec(specifier);
  if (!m) return null;
  const base = join(WEB_SRC, m[1], m[2]);
  for (const candidate of [`${base}.ts`, join(base, 'index.ts')]) {
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

function collectTsFiles(dir) {
  const out = [];
  const stack = [dir];
  while (stack.length > 0) {
    const current = stack.pop();
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.spec.ts')) out.push(full);
    }
  }
  return out;
}

/**
 * 頁面有沒有真的接後端 = 它（或它遞移引用的 shared 元件）import 了 `@core/<domain>.service`。
 *
 * **必須跟著 @shared 走**：`admin/subjects` 只有 11 行，內容是 `<app-subject-manager />` ——
 * 功能整個在共用元件裡。只看頁面目錄的話會把它誤判成空殼，然後有人（我）就會提議刪掉它。
 * 這種「頁面是薄容器、功能在 shared」的結構在本專案不只一處。
 *
 * 基礎設施 service（overlay/browser-state 之類）不算數：它們是純前端的。
 */
function pageDomainServices(page) {
  const [role, name] = page.split('/');
  const dir = join(rolePagesDir(role), name);
  if (!existsSync(dir)) return [];

  const found = new Set();
  const seen = new Set();
  const queue = collectTsFiles(dir);

  while (queue.length > 0) {
    const file = queue.pop();
    if (seen.has(file) || !existsSync(file)) continue;
    seen.add(file);

    const source = readFileSync(file, 'utf8');
    for (const m of source.matchAll(/from '@core\/([a-z-]+)\.service'/g)) {
      if (!INFRA_SERVICES.has(m[1])) found.add(m[1]);
    }
    // 跟著 @shared / @core 的引用往下追，才看得到薄容器頁面背後的真功能
    for (const m of source.matchAll(/from '(@(?:shared|core)\/[^']+)'/g)) {
      const resolved = resolveAlias(m[1]);
      if (resolved && !seen.has(resolved)) queue.push(resolved);
    }
  }

  return [...found].sort();
}

// 掛載一律走 mount()（強制宣告角色，見 check-harness 的 A7）；app.route 是舊寫法，
// 兩種都認才不會在轉換期間把「已掛載 API」全部算成 0
const mountedRoutes = existsSync(API_INDEX)
  ? [
      ...readFileSync(API_INDEX, 'utf8').matchAll(/(?:app\.route|mount)\('\/api\/([a-z-]+)'/g),
    ].map((m) => m[1])
  : [];

const diskPages = ROLES.flatMap((role) =>
  listDirs(rolePagesDir(role)).map((name) => `${role}/${name}`),
);
const diskRoutes = listRoutes();
const diskSpecs = walkSpecs(SPECS).filter((s) => !SPEC_EXEMPT.includes(s));

// ── 反向斷言：磁碟上的東西必須被藍圖認領，否則會靜默從統計消失 ──────────────────────────
const failures = [];
const claimed = {
  pages: new Set(AREAS.flatMap((a) => a.pages)),
  routes: new Set(AREAS.flatMap((a) => a.routes)),
  specs: new Set(AREAS.flatMap((a) => a.specs)),
};
for (const [label, disk, set] of [
  ['頁面', diskPages, claimed.pages],
  ['api route', diskRoutes, claimed.routes],
  ['spec', diskSpecs, claimed.specs],
]) {
  const orphans = disk.filter((x) => !set.has(x));
  if (orphans.length > 0) {
    failures.push(
      `${label} 未被任何功能區認領：${orphans.join(', ')}（加進 feature-map.mjs 的 AREAS）`,
    );
  }
}

function render() {
  const rows = AREAS.map((area) => {
    const pages = area.pages.filter((p) => diskPages.includes(p));
    const routes = area.routes.filter((r) => diskRoutes.includes(r));
    const mounted = routes.filter(
      (r) =>
        mountedRoutes.includes(MOUNT_ALIAS[r] ?? r) || mountedRoutes.includes(r.replace(/s$/, '')),
    );
    const specs = area.specs.filter((s) => diskSpecs.includes(s));
    const wired = pages.filter((p) => pageDomainServices(p).length > 0);

    let status;
    if (area.planned && pages.length === 0 && routes.length === 0) status = '⬜ 未開始';
    else if (pages.length === 0 && routes.length > 0) status = '🔌 僅後端';
    else if (pages.length > 0 && routes.length === 0) status = '🚧 空殼';
    else if (pages.length > 0 && wired.length === 0) status = '🚧 空殼';
    else if (pages.length > 0 && wired.length < pages.length) status = '🟡 部分接上';
    else status = '✅ 已接通';

    // 每個角色各自的狀態：有接後端 / 只有空殼 / 根本沒這個頁
    const byRole = Object.fromEntries(
      ROLES.map((role) => {
        const own = pages.filter((p) => p.startsWith(`${role}/`));
        if (own.length === 0) return [role, '—'];
        const ok = own.filter((p) => wired.includes(p)).length;
        if (ok === 0) return [role, '🚧'];
        return [role, ok === own.length ? '✅' : `🟡 ${ok}/${own.length}`];
      }),
    );

    return {
      area: area.name,
      byRole,
      wired: wired.length,
      api: mounted.length,
      specs: specs.length,
      status,
    };
  });

  const shells = rows.filter((r) => r.status.includes('空殼'));
  const roleCols = ROLES.map((r) => ROLE_LABELS[r]).join(' | ');

  /** 某個角色底下所有頁面都是空殼的功能區 */
  const shellsFor = (role) =>
    rows.filter((r) => r.byRole[role] === '🚧').map((r) => r.area);

  return [
    `| 功能區 | ${roleCols} | 已掛載 API | 規格 | 狀態 |`,
    `| --- | ${ROLES.map(() => '---').join(' | ')} | --- | --- | --- |`,
    ...rows.map(
      (r) =>
        `| ${r.area} | ${ROLES.map((role) => r.byRole[role]).join(' | ')} | ${r.api} | ${r.specs} | ${r.status} |`,
    ),
    '',
    `**共 ${AREAS.length} 個功能區：${rows.filter((r) => r.status.includes('已接通')).length} 個已接通、${shells.length} 個空殼、${rows.filter((r) => r.status.includes('未開始')).length} 個未開始。**`,
    '',
    ...ROLES.map(
      (role) =>
        `${ROLE_LABELS[role]}空殼（有頁面沒後端）：${shellsFor(role).join('、') || '無'}`,
    ),
    `未開始（MVP 有列，磁碟上完全不存在）：${
      rows
        .filter((r) => r.status.includes('未開始'))
        .map((r) => r.area)
        .join('、') || '無'
    }`,
    '',
    '> ✅ 該角色的頁面都 import 了 `@core/<domain>.service`；🚧 有頁面但完全沒接後端；',
    '> 🟡 部分接上；— 這個角色沒有這個功能的頁面。',
    '> 這張表只證明東西存不存在，**不證明**功能正確或完整。',
  ].join('\n');
}

const normalize = (t) =>
  t
    .split('\n')
    .map((l) =>
      l
        .trim()
        .replace(/-{2,}/g, '-')
        .replace(/[ \t]+/g, ' '),
    )
    .filter(Boolean)
    .join('\n');

// 測試要 import 這支檔案，所以主流程包起來 —— 跟 test-gate.mjs 同一個做法
export { AREAS, ROLES, diskPages, failures, render };

async function main() {
  const mode = process.argv.includes('--write') ? 'write' : 'check';
  const body = render();

  if (failures.length > 0 && mode !== 'write') {
    console.error(`✖ feature map 有 ${failures.length} 項問題：`);
    for (const f of failures) console.error(`  - ${f}`);
    process.exit(1);
  }

  if (!existsSync(ROADMAP)) {
    console.error('✖ kb/wiki/roadmap.md 不存在。');
    process.exit(1);
  }

  const source = readFileSync(ROADMAP, 'utf8');
  const from = source.indexOf(START);
  const to = source.indexOf(END);
  if (from === -1 || to === -1) {
    console.error('✖ kb/wiki/roadmap.md 缺少 FEATURE-MAP marker。');
    process.exit(1);
  }

  if (mode === 'write') {
    const { writeFileSync } = await import('node:fs');
    writeFileSync(
      ROADMAP,
      `${source.slice(0, from + START.length)}\n\n${body}\n\n${source.slice(to)}`,
    );
    console.log(`✓ 功能區現況表已重生（${AREAS.length} 個功能區）`);
  } else if (normalize(source.slice(from + START.length, to)) !== normalize(body)) {
    console.error('✖ kb/wiki/roadmap.md 的功能區現況表過期。重生：npm run harness:write');
    process.exit(1);
  } else {
    console.log(`✓ 功能區現況表同步（${AREAS.length} 個功能區）`);
  }
}

if (process.argv[1]?.endsWith('feature-map.mjs')) await main();
