#!/usr/bin/env node
/**
 * Knowledge-base gate for kb/.
 *
 *   node tools/agent-harness/kb-gate.mjs           # --check (default): 缺欄位或索引過期 → exit 1
 *   node tools/agent-harness/kb-gate.mjs --write    # 補齊缺少的 frontmatter + 重生 kb/index.md
 *
 * 設計取捨：frontmatter 由既有內容**推導**（title 取 H1、summary 取第一段、updated 取 git
 * 最後提交日），不是留白等人填。一個沒人能弄綠的 gate 會被忽略，那比沒有 gate 更糟。
 * 推導錯了就手改 —— 本腳本只補「缺少的」欄位，永遠不覆寫既有值。
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const KB = join(ROOT, 'kb');
const INDEX = join(KB, 'index.md');
const REQUIRED = ['title', 'summary', 'category', 'status', 'updated'];

const START =
  '<!-- KB-INDEX:START — auto-generated by tools/agent-harness/kb-gate.mjs; do not hand-edit -->';
const END = '<!-- KB-INDEX:END -->';

/** 目錄 → 分類與預設狀態。順序即索引順序（canonical order，不依賴 readdir）。 */
const CATEGORIES = [
  { prefix: 'kb/architecture/', category: 'architecture', status: 'active', label: '架構與法條' },
  { prefix: 'kb/rules/', category: 'rule', status: 'active', label: '業務規則' },
  { prefix: 'kb/flows/', category: 'flow', status: 'active', label: '流程' },
  { prefix: 'kb/specs/', category: 'spec', status: 'active', label: '功能規格' },
  { prefix: 'kb/wiki/lessons/', category: 'lesson', status: 'active', label: '工程教訓' },
  { prefix: 'kb/wiki/', category: 'pattern', status: 'active', label: '實作模式' },
  { prefix: 'kb/', category: 'guide', status: 'active', label: '總覽與指引' },
];

const mode = process.argv.includes('--write') ? 'write' : 'check';
const failures = [];
const fail = (message) => failures.push(message);

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name.endsWith('.md')) out.push(full);
  }
  return out.sort();
}

function classify(relPath) {
  return CATEGORIES.find((entry) => relPath.startsWith(entry.prefix));
}

function parseFrontmatter(source) {
  const match = /^---\n([\s\S]*?)\n---\n?/.exec(source);
  if (!match) return { fields: {}, body: source, raw: null };
  const fields = {};
  for (const line of match[1].split('\n')) {
    const pair = /^([a-z_]+):\s*(.*)$/.exec(line);
    if (pair) fields[pair[1]] = pair[2].trim();
  }
  return { fields, body: source.slice(match[0].length), raw: match[1] };
}

function lastCommitDate(relPath) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%ad', '--date=short', '--', relPath], {
      cwd: ROOT,
      encoding: 'utf8',
    }).trim();
    if (out) return out;
  } catch {
    /* untracked or no git — fall through */
  }
  return new Date(statSync(join(ROOT, relPath)).mtime).toISOString().slice(0, 10);
}

/** H1 當標題；沒有 H1 就用檔名。 */
function deriveTitle(body, relPath) {
  const heading = /^#\s+(.+)$/m.exec(body);
  return heading ? heading[1].trim() : relPath.split('/').pop().replace(/\.md$/, '');
}

/**
 * 第一段散文；截到 140 字。
 *
 * 跳過標題、引言、表格、程式碼圍籬與清單項，但**不**跳過粗體開頭的句子 —— 有些頁面的第一段
 * 就是 `**Goal:** …` 這種粗體標籤句，把它當清單跳過會讓 summary 撿到文件中段的無關句子。
 */
function deriveSummary(body, title) {
  const SKIP = /^(#|>|\||```|[-*+] |\d+\. )/;
  const LABEL = /^\*\*[^*]+\*\*\s*[:：]/;

  for (const block of body.split(/\n\s*\n/)) {
    const lines = block.trim().split('\n').filter(Boolean);
    if (lines.length === 0 || SKIP.test(lines[0])) continue;
    // 多行、每行都是 `**標籤**: 值` → 這是 metadata 區塊（規格頁的路徑/角色/分組），不是摘要。
    // 單行的 `**Goal:** …` 則是真正的摘要，必須留下。
    if (lines.length > 1 && lines.every((line) => LABEL.test(line))) continue;

    const text = lines.join(' ').replace(/\*\*/g, '').replace(/\s+/g, ' ').trim();
    if (!text) continue;
    return text.length > 140 ? `${text.slice(0, 137)}…` : text;
  }
  return title;
}

function quote(value) {
  return /[:#]/.test(value) ? `'${value.replace(/'/g, "''")}'` : value;
}

// ── 掃描並補齊 ───────────────────────────────────────────────────────────────────────────
const pages = [];

for (const absolute of walk(KB)) {
  const relPath = relative(ROOT, absolute);
  if (relPath === 'kb/index.md') continue;

  const rule = classify(relPath);
  const source = readFileSync(absolute, 'utf8');
  const { fields, body } = parseFrontmatter(source);

  const derived = {
    title: fields.title || deriveTitle(body, relPath),
    category: fields.category || rule.category,
    status: fields.status || rule.status,
    updated: fields.updated || lastCommitDate(relPath),
  };
  derived.summary = fields.summary || deriveSummary(body, derived.title);

  const missing = REQUIRED.filter((field) => !fields[field]);

  if (missing.length > 0) {
    if (mode === 'write') {
      const merged = REQUIRED.map((field) => `${field}: ${quote(derived[field])}`).join('\n');
      writeFileSync(absolute, `---\n${merged}\n---\n\n${body.replace(/^\n+/, '')}`);
    } else {
      fail(`${relPath} 缺 frontmatter 欄位：${missing.join(', ')}`);
    }
  }

  pages.push({ relPath, ...derived, label: rule.label });
}

// ── K3. 索引連結必須解得開 ───────────────────────────────────────────────────────────────
// 索引的連結是相對於 kb/index.md 的。改過一次目錄名之後，剝前綴的 regex 沒跟著改，整份索引
// 的連結全部指向 kb/kb/… —— 而 frontmatter 與索引比對都還是綠的。斷鏈要由 gate 自己抓。
for (const page of pages) {
  const href = page.relPath.replace(/^kb\//, '');
  if (!existsSync(join(KB, href))) {
    fail(`索引連結解不開：${href}（來自 ${page.relPath}）`);
  }
}

// ── 索引 ─────────────────────────────────────────────────────────────────────────────────
function renderIndex() {
  const lines = [];
  for (const { label } of CATEGORIES) {
    const group = pages.filter((page) => page.label === label);
    if (group.length === 0) continue;
    if (lines.length > 0) lines.push('');
    lines.push(`### ${label}（${group.length}）`, '');
    for (const page of group) {
      const flag = page.status === 'active' ? '' : ` \`${page.status}\``;
      lines.push(
        `- [${page.title}](${page.relPath.replace(/^kb\//, '')})${flag} — ${page.summary}`,
      );
    }
  }
  return lines.join('\n');
}

const indexBody = renderIndex();

if (!existsSync(INDEX)) {
  if (mode === 'write') {
    writeFileSync(
      INDEX,
      [
        '---',
        'title: Clessia 文件索引',
        'summary: kb/ 全部頁面的分類索引，由 tools/agent-harness/kb-gate.mjs 生成。',
        'category: guide',
        'status: active',
        `updated: ${new Date().toISOString().slice(0, 10)}`,
        '---',
        '',
        '# Clessia 文件索引',
        '',
        '收錄標準、frontmatter 欄位、新頁面該放哪 → [`schema.md`](schema.md)。',
        '',
        START,
        '',
        indexBody,
        '',
        END,
        '',
      ].join('\n'),
    );
  } else {
    fail('kb/index.md 不存在。生成：npm run kb:write');
  }
} else {
  const source = readFileSync(INDEX, 'utf8');
  const from = source.indexOf(START);
  const to = source.indexOf(END);
  if (from === -1 || to === -1) {
    fail('kb/index.md 缺少 KB-INDEX marker。');
  } else if (mode === 'write') {
    writeFileSync(
      INDEX,
      `${source.slice(0, from + START.length)}\n\n${indexBody}\n\n${source.slice(to)}`,
    );
  } else {
    // 比對內容不比對版面 —— PostToolUse 的 prettier 會重排這個檔
    const normalize = (text) =>
      text
        .split('\n')
        .map((line) => line.trim().replace(/[ \t]+/g, ' '))
        .filter(Boolean)
        .join('\n');
    if (normalize(source.slice(from + START.length, to)) !== normalize(indexBody)) {
      fail('kb/index.md 索引過期。重生：npm run kb:write');
    }
  }
}

// ── 回報 ─────────────────────────────────────────────────────────────────────────────────
if (mode === 'write') {
  console.log(`✓ KB 已同步（${pages.length} 頁）`);
  process.exit(0);
}
if (failures.length > 0) {
  console.error(`✖ KB gate 有 ${failures.length} 項不同步：`);
  for (const message of failures.slice(0, 15)) console.error(`  - ${message}`);
  if (failures.length > 15) console.error(`  … 另外 ${failures.length - 15} 項`);
  process.exit(1);
}
const active = pages.filter((page) => page.status === 'active').length;
console.log(`✓ KB gate 全綠（${pages.length} 頁，${active} 頁 active）`);
