import { chromium } from 'playwright';
const [state, out] = process.argv.slice(2);
const b = await chromium.launch();
const ctx = await b.newContext({ storageState: state, viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
const p = await ctx.newPage(); p.setDefaultTimeout(8000);
await p.goto('http://localhost:4200/admin/fee-templates', { waitUntil: 'networkidle' }); await p.waitForTimeout(1500);
const chev = p.locator('app-responsive-table button').filter({ has: p.locator('.pi-chevron-right, .pi-angle-right, .pi-chevron-down') });
console.log('chevrons', await chev.count());
await p.locator('app-responsive-table button').first().click(); await p.waitForTimeout(500);
const txt = await p.locator('body').innerText();
console.log(JSON.stringify([...txt.matchAll(/報名[^\n]*|\d+ 筆報名/g)].map((m) => m[0])).slice(0, 300));
await p.screenshot({ path: `${out}/f14-m-open.png`, fullPage: true });
await b.close();
