import { chromium } from 'playwright';
const [state] = process.argv.slice(2);
const b = await chromium.launch();
const ctx = await b.newContext({ storageState: state, viewport: { width: 1280, height: 800 }, reducedMotion: 'reduce' });
const p = await ctx.newPage();
p.on('response', async (r) => { if (r.url().includes('/api/academy-exams?')) { const j = await r.json(); console.log('API', j.data.length, JSON.stringify(j.data.filter((e) => e.classes?.length).slice(0, 3).map((e) => [e.name, e.scopeNote, e.classCount, e.classes.map((c) => c.name)]))); } });
await p.goto('http://localhost:4200/admin/grades/exams', { waitUntil: 'networkidle' }); await p.waitForTimeout(1500);
const cells = await p.locator('div.col-start-1.min-w-0').evaluateAll((els) => els.map((e) => e.innerText.replace(/\n/g, ' | ')).slice(0, 30));
console.log(cells.filter((c) => !c.startsWith('0 個班')).slice(0, 6).join('\n'));
await b.close();
