import { chromium } from 'playwright';
const [state] = process.argv.slice(2);
const b = await chromium.launch();
const ctx = await b.newContext({ storageState: state, viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
const p = await ctx.newPage();
await p.route('**/api/me/billing*', async (r) => { const res = await r.fetch(); const j = await res.json(); const d = j.data; if (d.length >= 3) { d[2].status = 'paid'; d[2].netPaid = d[2].total; d[2].payments = [{ id: 'p2', kind: 'payment', amount: d[2].total, method: 'transfer', paidAt: '2026-09-20', receiptNo: 1 }]; } await r.fulfill({ response: res, json: j }); });
await p.goto('http://localhost:4200/parent/payments', { waitUntil: 'networkidle' }); await p.waitForTimeout(800);
const sw = p.locator('button.child-switcher__badge--interactive'); await sw.click(); await p.locator('.child-switcher__list-item', { hasText: '張宇軒' }).click(); await p.waitForTimeout(1500);
await p.locator('.payments__row').nth(2).click(); await p.waitForTimeout(800);
const r = await p.evaluate(() => { const q = (s) => document.querySelector(s); const o = {}; const dr = q('.p-drawer'); const rc = (e) => { const x = e.getBoundingClientRect(); return [Math.round(x.top*10)/10, Math.round(x.height*10)/10]; }; o.drawer = rc(dr); o.detail = rc(q('.payments__detail')); for (const c of ['title','status','items','total','due','payments','close']) { const e = q('.payments__detail-' + c); o[c] = e ? rc(e) : null; } o.header = q('.p-drawer-header') ? rc(q('.p-drawer-header')) : null; o.content = q('.p-drawer-content') ? rc(q('.p-drawer-content')) : null; return o; });
console.log(JSON.stringify(r));
await b.close();
