import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
const [linkFile, name] = process.argv.slice(2);
const link = readFileSync(linkFile, 'utf8').match(/https?:\/\/[^\s]+/)[0];
const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } }); const p = await ctx.newPage();
await p.goto(link, { waitUntil: 'networkidle' }); await p.waitForTimeout(800);
await p.evaluate(() => localStorage.setItem('clessia:active-role', 'admin'));
await p.goto('http://localhost:4200/admin/dashboard', { waitUntil: 'networkidle' }); await p.waitForTimeout(800);
const items = await p.locator('aside.sidebar a.sidebar__item').evaluateAll((as) => as.map((a) => a.textContent.trim()));
await p.goto('http://localhost:4200/admin/staff', { waitUntil: 'networkidle' }); await p.waitForTimeout(800);
console.log(name, '| 側欄', items.length, items.includes('人員管理') ? '含人員管理' : '無人員管理', '| /admin/staff →', new URL(p.url()).pathname);
await b.close();
